[package]
name = "gtfs-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
chrono = {version = "0.4.41", features = ["serde"]}
dotenvy = "0.15.7"
polars = {version = "0.50.0", features = ["dtype-struct"]}
reqwest = "0.12.23"
serde = "1.0.219"
sqlx = {version = "0.8.6", features = ["postgres", "runtime-tokio", "chrono"]}
tokio = {version = "1.47.1", features = ["rt-multi-thread", "macros"]}
zip = "4.6.1"
