[package]
edition      = "2021"
name         = "display"
rust-version = "1.89"
version      = "0.1.0"

[[bin]]
name = "display"
path = "./src/bin/main.rs"

[dependencies]
esp-bootloader-esp-idf = { version = "0.2.0", features = ["esp32s2"] }
esp-hal                = { version = "=1.0.0-rc.0", features = ["esp32s2", "unstable", "log-04"] }

esp-backtrace = {version = "0.17.0", features = [
  "esp32s2",
  "exception-handler",
  "panic-handler",
  "println",
]}
esp-println = {version = "0.15.0", features = ["esp32s2", "log-04"]}
ws2812-spi = "0.5.1"
smart-leds = "0.4.0"
log = "0.4.28"
esp-alloc = "0.8.0"
mipidsi = "0.9.0"
embedded-graphics = "0.8.1"
embedded-hal = "1.0.0"
embedded-hal-bus = "0.3.0"
u8g2-fonts = "0.7.2"
xtensa-lx-rt = { version = "0.19.0", features = ["esp32s2"] }
smoltcp = { version = "0.12.0", default-features=false, features = ["proto-ipv4", "socket-tcp", "socket-icmp", "socket-udp", "medium-ethernet", "proto-dhcpv4", "socket-raw", "socket-dhcpv4"] }
esp-wifi = { version = "0.15.0", features = ["xtensa-lx-rt", "esp32s2", "wifi", "smoltcp"] }
blocking-network-stack = { git = "https://github.com/bjoernQ/blocking-network-stack.git", rev = "b3ecefc" }
embedded-io = "0.6.1"

[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units    = 1     # LLVM can perform better optimizations using a single thread
debug            = 2
debug-assertions = false
incremental      = false
lto              = 'fat'
opt-level        = 's'
overflow-checks  = false
